name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          check-latest: true
          cache: true

      - name: Lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.5.0
          args: ./...

      - name: Security Scan
        uses: securego/gosec@v2.26.1
        with:
          args: ./...

      - name: Unit Tests
        run: make test-unit

      - name: Integration Tests
        env:
          PITCHSTACK_API_BASE_URL: https://api.pitchstack.gg
          PITCHSTACK_API_TOKEN: TEST
          PITCHSTACK_CARD_ID: sink-below-r
          PITCHSTACK_CARD_SEARCH_TERM: sink
          PITCHSTACK_PRINTING_ID: FTTgbMdc7HPFD8bfLrQNK
          PITCHSTACK_PHYSICAL_CARD_ID: pc_FTTgbMdc7HPFD8bfLrQNK
          PITCHSTACK_NONEXISTENT_CARD_ID: hahalol
        run: make test-integration
